### ISSUE TITLE
Allow `pdf`  to return scores for multiple classes in  one shot

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#137]
At the moment `pdf` is well adapted for binary, but in the multiclass case, we may want to be able to do something like 

```julia
pdf(yhat, labels)
```

and get a vector of floating point scores with `c` entries where `c` is the  number of classes.

**Comment by ablaom** [comment]
I think some care should be taken here as `pdf` is part of another package's interface, namely Distributions.jl. The suggestion above could be construed as type piracy, no? I mean, `yhat` is not a distribution, for starters. 

Is there a pressing use case for this functionality? I wonder if this is more a question of users wanting the output in a form with which they are familiar, rather than a form they actually need it in. But I am happy to be contradicted. 

For occasional use, `hcat([pdf.(yhat, c) for c in labels]...)` is not so bad, IMHO.

**Comment by tlienart** [comment]
I think that's fair enough, the one extra case where I could see this being useful in some form is if you pass on the results to a higher level learner where the score per class would be features (maybe that's convoluted). 

Maybe this could be solved by using another name which would not clash like `get_scores` (that would apply to a vector of univariate finite) or `predict_scores` (which would do  both  in one shot) defined precisely as you said.

**Comment by ablaom** [comment]
I think a remedy proposed at https://github.com/alan-turing-institute/MLJ.jl/issues/511#issuecomment-622666705 would allow us to avoid type piracy here.

**Comment by ablaom** [comment]
Resolved by above PR merge. Syntax as suggested by issue poster.
