### ISSUE TITLE
models(is_pure_julia) stopped working

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJBase.jl#157]
MWE:

```julia
using MLJ, MLJBase
models(is_pure_julia)
```
>TypeError: non-boolean (Missing) used in boolean context

>Stacktrace:
 [1] filter(::MLJModels.var"#12#14"{Tuple{typeof(is_pure_julia)}}, ::Array{NamedTuple,1}) at ./array.jl:2346
 [2] models(::Function) at /Users/julio.hoffimann@ibm.com/.julia/packages/MLJModels/ayF3A/src/model_search.jl:149
 [3] top-level scope at In[46]:1

**Comment by tlienart** [comment]
@ablaom consider

```julia
julia> using MLJ, MLJBase
julia> is_pure_julia(models()[1])
missing

julia> models()[1].is_pure_julia
false
```

should be easy to fix

**Comment by ablaom** [comment]
This is not a bug, as explained in our slack correspondence copied below:

The correct syntax is `models(m->m.is_pure_julia)`. The objects filtered by `models(...)` are not literally model types (to which the `is_pure_julia` trait function can be applied) because these are not in scope before loading, but *named-tuples representing the model metadata* (“proxies” for the actual unloaded models). For each bona-fide model trait, the named tuple has a key. If you do models() you get all such named tuples.

See also https://alan-turing-institute.github.io/MLJ.jl/dev/model_search/
