### ISSUE TITLE
Possibly add `fit_predict`

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#161]
Trying to interface with Sklearn's unsupervised models I realised that some of them only have `fit_predict`. E.g.: AgglomerativeClustering, DBSCAN,  OPTICS,  SpectralClustering, there's even two that don't have anything else than `fit` (SpectralCoclustering and Biclustering)

This actually makes sense, once you've computed something like a linkage-tree, you can only "predict" labels on the data it was trained with; and those labels are known at training time. 

I guess there's two ways forward:

1. keep things as they are and have some unsupervised models which *only* have a `fit` method, the user then has to  extract relevant things from the fitted params (e.g. `labels`)
1. add a `fit_predict` method (which does the same thing as 1 except it's got a name)

For now I've gone with (1) to keep things simple but we may want to change that.

**Comment by ablaom** [comment]
@tlienart Thanks for explaining why some models *only* have `fit_predict`.

I think option 2, while convenient, does not make sense unless it is clear in every case what arguments `fit_predict` is going to be permitted, and what the return value is going to be. Is this the case? Probably not in every conceivable case. 

Otherwise, option 2, while it is less convenient and maybe more mysterious (how do I get my results?) can be more informative, because `fitted_params` returns a named tuple (which could include model-specific  *methods*). 

So my vote would be for 1.

**Comment by tlienart** [comment]
ok
