### ISSUE TITLE
Remove two letter measures

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#187]
I actually did this in the refactoring but https://github.com/alan-turing-institute/MLJBase.jl/pull/186 reverted it. 

I think it's a bad idea to export `tp, fp, tn, fn` as these names are very likely to clash.

Thoughts?

(PS: I should have raised this during the call but forgot)

**Edit**: a counter argument could go  as follows: we encourage people who use MLJBase to *only* use it as an *import* and therefore everything is qualified?

**Comment by ablaom** [comment]
@tlienart 

In general I don't like any of these abbreviations. I just assumed many of them are entrenched. The two letter case is extreme and you have a valid point re clashes. But then the `name` trait should be bound to a different alias, because that's what comes up when you search using `measures()` and users are likely to expect these names to be exported.  By convention, I have also bound the doc strings to `name` bindings.

I propose removing the export of tp, fp, tn, fn, but leaving the other 3 letter abbreviations. But let's bind `name` and docstrings to more informative labels (keeping the abbreviated forms as aliases, so not really breaking anything).

Does this sound reasonable?

**Comment by tlienart** [comment]
yes that sounds reasonable
