### ISSUE TITLE
join method for one-dimensional ranges

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#211]
In private correspondence I received this suggestion:

I understand what you’re saying with respect to specifying values explicitly in range. Now could we have a `merge` operation which merges two ranges? See adapted examples below.

julia> r1 = range(Int, :lambda, values=[1, 50, 10_000])
julia> iterator(r1)
3-element Array{Int64,1}:
   1
  50
10000

julia> r2 = range(Int, :lambda, lower=0.1, upper=100_000, scale=:log) 
julia> iterator(r2, 5)
5-element Array{Int64,1}:
    0
    3
  100
 3162
100000

### NEW STUFF ?

julia> r = join(r1, r2)
julia> iterator(r, 5)
0
1
3
50
100

**Comment by tlienart** [comment]
Note that I'm thinking it may be easier to just do something like

```
julia> rc = range(Int, :lambda, lower=0.1, upper=100_000, scale=:log, values=[1,5,10_000])
```

with the meaning that if you add the keyword `values` then you *require* these values to be present. 

I think the initial thing I suggested is a bit trickier because you'd need to pop stuff from both iterators, check which ones come first, build a queue or something, might be more pain than is worth. Also I'm not sure what use case would need this in full generality beyond the example above?

**Comment by ablaom** [comment]
Going to close for now. In random search and grid, at least, you can specify two ranges for the same field, which effectively joins them.
