### ISSUE TITLE
Better error message for predict_mean in the case of a classifier

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#40]
While implementing an interface for NearestNeighbors, I was testing `predict_mode` (works fine) and then to check, tested `predict_mean` which didn't work (that's fine) but the error message would be cryptic for non-devs:

```
MethodError: no method matching iterate(::UnivariateFinite{String,UInt32,Float64})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:600
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:600
  iterate(!Matched::ExponentialBackOff) at error.jl:218
  ...
mean(::typeof(identity), ::UnivariateFinite{String,UInt32,Float64}) at Statistics.jl:58
mean(::UnivariateFinite{String,UInt32,Float64}) at Statistics.jl:42
_broadcast_getindex_evalf at broadcast.jl:625 [inlined]
_broadcast_getindex at broadcast.jl:598 [inlined]
getindex at broadcast.jl:558 [inlined]
copy at broadcast.jl:848 [inlined]
materialize at broadcast.jl:814 [inlined]
predict_mean(::KNNClassifier, ::Tuple{NearestNeighbors.KDTree{StaticArrays.SArray{Tuple{3},Float64,1,3},Distances.Euclidean,Float64},CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}}}, ::Tables.MatrixTable{Array{Float64,2}}) at MLJBase.jl:152
top-level scope at NearestNeighbors.jl:46
```

There may be more than one problem here but it may make sense to catch that the model is a classsifier, show a warning, and return the output of `predict_mode` ?

**Comment by ablaom** [comment]
This  is a little tricky because there is nothing currently in the model metadata to say whether the raw probabilistic predictions (distributions) support `mode` or `median` or `mean`. We  could inspect a particular prediction, but even in the usual case of a `Distribution` object, I don't think there's anything in the explicitly in the Distributions interface to tell us whether these are supported. 

I suggest we just do try and catch,  reporting the likely cause of the error when tripped. Any better ideas?
