### ISSUE TITLE
info/info_dict  bottleneck

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#76]
In view of the investigation https://github.com/alan-turing-institute/MLJModels.jl/issues/112 it seems that these functions are much slower than they should be; this warrants an investigation.

I haven't looked in depth but a first thing to note is that calling these functions seems to  allocate like crazy; which  seems weird.

Anyway proper benchmarking of `info_dict` and `info` and fixes would probably be a good idea

**Comment by Arkoniak** [comment]
I doubt it is good first issue :-))

Some investigation

```julia
using MLJBase
using BenchmarkTools

struct DummyProb <: Probabilistic end

@btime info_dict($DummyProb)
#  84.096 ms (171929 allocations: 10.68 MiB)
```

After diiging through `info_dict` it turns out that most time expensive method is `implemented_methods` which in turn expensive because it uses `InteractiveUtils` `methodswith`

```julia
@btime methodswith($DummyProb)
#   83.581 ms (171701 allocations: 10.67 MiB)
```

So, unless `methodswith` can be avoided, there is no way to make this function faster.

**Comment by tlienart** [comment]
That’s a relative newcomer I think (?) anyway 80ms for that is atrocious; @ablaom do you reckon we could get around this? What’s the use case for having methodswith in the infos? 

Also I wonder whether we could do a lazy info dict where (expensive) things are only computed upon explicit querying

**Comment by Arkoniak** [comment]
For future references, it is rather easy to implement lazy dict with `DefaultDict` from `DataStructures.jl`

instead of
```julia
    return LittleDict{Symbol, Any}(trait => getfield(MLJBase, trait)(M)
                                    for trait in MLJModelInterface.MODEL_TRAITS)
```

use
```julia
dd = DefaultDict{Symbol, Any}(passkey=true) do key
         getfield(MLJBase, key)(DummyProb)
     end

return dd
```

The drawback of this approach is that `keys` and `iterate` wouldn't work correctly and you need to know all keys beforehand. Since `info_dict` is internal structure, may be it's ok.

Alternatively, one can implement all `DefaultDict` functionality plus some defaults for keys. But this requires some work to carefully forward all necessary methods (only sketch of the idea)

```julia
struct LazyDict{K, V, M} <: AbstractDict{K, V}
    d::Dict{K, V}
    keys::Vector{K}
    m::M
end

Base.:keys(d::LazyDict) = union(keys(d.d), d.keys)

function Base.:getindex(d::LazyDict, k)
    if k in keys(d.d)
        return d.d[k]
    elseif k in d.keys
        d.d[k] = getfield(MLJBase, k)(d.m)
        return d.d[k]
    else
        error("key $k not found")
    end
end

# generic functions
length(d::LazyDict) = ...
iterate...
```

**Comment by tlienart** [comment]
@Arkoniak we discussed this briefly in the weekly call and would be happy to review a PR in this regards; the keys/iterate support is kind of secondary because we use this more as just an information store. 

Also we don't actually use this implemented_methods at the moment but probably better to leave it there for now.

Thanks!

**Comment by ablaom** [comment]
Closing. See #227
