### ISSUE TITLE
Additional traits  for measures

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJBase.jl#98]
I'm not a big fan of traits but given we're doing that everywhere we might as well try to be complete? for finite metrics should we maybe add:

* multiclass / binary
* dependent on labelling or not
* robust to imbalance / not
 - [x] a docstring like for mljmodels indicating the formula

**Comment by ablaom** [comment]
Thanks for that.

I think the multiclass/binary distinction is implicit in `target_scitype`. For example, 

```julia
julia> info(LossFunctions.ZeroOneLoss())
(name = "ZeroOneLoss",
 target_scitype = AbstractArray{#s56,N} where N where #s56<:Finite{2},
 prediction_type = :probabilistic,
 orientation = :loss,
 reports_each_observation = true,
 is_feature_dependent = false,
 supports_weights = true,)
```

So, if you parse this, you see `target_scitype` is `AbstractVector{<:Finite{2}}`, making this a binary loss function. If the order really mattered (`true_positive` for example) then you would need to declare `AbstractVector{<:OrderedFactor{2}}`, so perhaps this also takes care of labelling, for our purposes, no?

The other two traits make sense.

We should also add a `measures()` method analogous to `models()` to list the meaures with their traits. For this we probably need a "registry" because `Measure` subtypes do not include externally defined measures (currently those in LossFunctions).
